from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv
from prompts import *
from states import *
from langgraph.graph import StateGraph, END
from tools import *
from langchain.agents import create_agent
from langchain_core.globals import set_verbose, set_debug

load_dotenv()

GROQ_API_KEY=os.getenv("GROQ_API_KEY")

os.environ["GROQ_API_KEY"]=GROQ_API_KEY
llm=ChatGroq(model="openai/gpt-oss-120b")

# set_debug(True)
# set_verbose(True)

def planner_agent(state:dict)-> dict:
    user_prompt=state["user_prompt"]
    resp=llm.with_structured_output(Plan).invoke(planner_prompt(user_prompt))
    return {
        "plan":resp
    }

def architect_agent(state:dict)-> dict:
    plan:Plan=state["plan"]
    resp=llm.with_structured_output(TaskPlan).invoke(architect_promt(plan))
    if resp is None:
        raise ValueError("No implementation steps generated by the architect agent.")
    
    resp.plan=plan
    return {
        "task_plan":resp
    }

def coder_agent(state:dict)-> dict:
    coder_state: CoderState = state.get("coder_state")
    if coder_state is None:
        coder_state = CoderState(task_plan=state["task_plan"], current_step_idx=0)

    steps = coder_state.task_plan.implementation_steps

    if coder_state.current_step_idx >= len(steps):
        return {"coder_state": coder_state, "status": "DONE"}
    
    current_task = steps[coder_state.current_step_idx]
    existing_content = read_file.run(current_task.filepath)

    user_prompt=(
        f"Task: {current_task.task_description}\n"
        f"File: {current_task.filepath}\n"
        f"Existing content:\n{existing_content}\n"
        "Use write_file(path, content) to save your changes."
    )
    system_prompt=coder_system_prompt()
    coder_tools=[read_file,write_file,list_files,get_current_directory]
    react_agent=create_agent(model=llm, tools=coder_tools)
    react_agent.invoke({"messages": [{"role": "system", "content": system_prompt},
                                     {"role": "user", "content": user_prompt}]})
    
    coder_state.current_step_idx += 1
    return {"coder_state": coder_state}

graph=StateGraph(dict)
graph.add_node("planner",planner_agent)
graph.add_node("architect",architect_agent)
graph.add_node("coder",coder_agent)
graph.set_entry_point("planner")
graph.add_edge("planner","architect")
graph.add_edge("architect","coder")
graph.add_conditional_edges(
    "coder",
    lambda s: "END" if s.get("status") == "DONE" else "coder",
    {"END": END, "coder": "coder"}
)
app=graph.compile()

user_prompt="create a simple calculator web application using HTML,CSS,Javascript"

result=app.invoke({"user_prompt":user_prompt,
                   "recursion_limit":100})

print(result)