# -*- coding: utf-8 -*-
"""chromaDB.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BkcGNlWm6EpFCjHG1lpASVJeq7LLxRpe
"""

# !pip -q install chromadb google-genai langchain-community tiktoken langchain-chroma langchain-google-genai

# !pip show google-genai

# !wget -q https://www.dropbox.com/s/vs6ocyvpzzncvwh/new_articles.zip

# !unzip -q new_articles.zip -d new_articles

import os
os.environ['GEMINI_API_KEY']=""

from langchain_chroma import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings
from langchain_community.document_loaders import DirectoryLoader
from langchain_community.document_loaders import TextLoader

loader=DirectoryLoader("/content/new_articles", glob="./*.txt", loader_cls=TextLoader)

document=loader.load()

document

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter=RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
text=text_splitter.split_documents(document)

text

# creating DB
persist_directory='db'
embeddings = GoogleGenerativeAIEmbeddings(model="models/gemini-embedding-001")
# BATCH_SIZE=50
# def add_to_chroma_in_batches(vector_store, documents):
#     for i in range(0, len(documents), BATCH_SIZE):
#         batch = documents[i : i + BATCH_SIZE]
#         vector_store.add_documents(batch)

# vector_store = Chroma(
#     embedding_function=embeddings,
#     persist_directory=persist_directory
# )
vector_db=Chroma.from_documents(documents=text,embedding=embeddings,persist_directory=persist_directory)
# add_to_chroma_in_batches(vector_store,text)

vector_db.persist()
vector_db=None

#load persisted database from disk
vector_db=Chroma(persist_directory=persist_directory,embedding_function=embeddings)

retrievar=vector_db.as_retriever()
docs=retrievar.get_relevant_documents("How much money did microsoft raised")

"""## deleteing db"""

!zip -r db.zip ./db

vector_db.delete_collection()
vector_db.persist()

#delete directory
!rm -rf db/